### ISSUE TITLE
Javascript method is missing scanBarcode call.

### ISSUE THREAD

**Issue by LouisLiuTO** [DavidBriglio/cordova-plugin-ios-simple-scanner#1]
Hi David,

The plugin is great, after I did some Swift code converting, and fix one missing method name.

The Readme page missed the scanBarcode method name, the correct one should be:
cordova.plugins.ios.simpleScanner.scanBarcode("landscapeLeft", true, successCallback, errorCallback);

Also the comma should be replaced by "+" in the below console.log();

From:
var successCallback = function(value) {
    console.log("Format Found: " + value.format, "Data: " + value.data);
};
To:
var successCallback = function(value) {
    console.log("Format Found: " + value.format + "Data: " + value.data);
};

Thanks for the plugin, I am looking forward for all other code formats to be supported.

Louis Liu

**Comment by DavidBriglio** [comment]
Ah you are correct, the method name is not in the documentation! As for the comma, it is not a mistake since the console log method can take 'n' number of arguments, and will separate them out in the output. I will change this however, to avoid any confusion.

Thank you very much for your feedback! 😃

**Comment by LouisLiuTO** [comment]
Hi David, 

Thanks for fixing it.

Just a thought after wondering around for finding a nice solution that can scan all kinds bar codes.
There is Cordova barcode plugin, which supports most bar code formats, but PDF417 in iOS build.
https://github.com/hypery2k/cordova-barcodescanner-plugin

Would it be good if you can fork this plugin and integrate your iOS swift code into it? 

Cheers.

**Comment by DavidBriglio** [comment]
I have considered doing so in the past, but I wanted to create this plugin in its place in order to simplify the code and usage of the plugin. I may in the future try to add this functionality to a PR, but I want to focus my time on expanding this current plugin before I focus on others.
