### ISSUE TITLE
Please update to SWIFT 3 or more 

### ISSUE THREAD

**Issue by singuyenhoang** [DavidBriglio/cordova-plugin-ios-simple-scanner#2]
Project is using SWIFT2x that is not compatible with Xcode 9. Could you help convert to SWIFT3x or more. Thank you very much 🥇

**Comment by singuyenhoang** [comment]
Hello David,

I’m not familiar with Native code of IOS, then it’s impossible for me to convert SWIFT2x to 3x.
I re-download Xcode 8, and tried Edit->Convert->Current Swift syntax on Xcode, but there are many errors and i really don’t know how to handle them :((
I just use XCODE to compile Cordova project to debug on simulator.

So i really appreciate if you can help.

Thanks again
Nguyen Hoang

**Comment by DavidBriglio** [comment]
With my testing it seems to work fine when setting 'Build Settings > SWIFT_VERSION' to Swift 3.2. I will look into this further to make sure the code is up to date.

Thank you for your feedback!

**Comment by DavidBriglio** [comment]
I will be updating this to use swift version 4.2.

**Comment by DavidBriglio** [comment]
Version 1.2.1 contains swift 4.2 code and promise logic.
