### ISSUE TITLE
Cordova plugin ios simple scanner

### ISSUE THREAD

**Issue by prashant1706** [DavidBriglio/cordova-plugin-ios-simple-scanner#3]
Hi There, 

Can we have the Plugin src file avaialbe for objective C project as well ? 

Thanks

**Comment by DavidBriglio** [comment]
This is not necessary to use the plugin. If you are looking for a guide to implement this yourself, there are plenty of guides online that show how this is done, such as [this one](https://www.appcoda.com/qr-code-ios-programming-tutorial/).
